nelson/base/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.ShopView.as_view(), name='shop'),
    path('<slug:slug>/', views.ProductDetails.as_view(), name='products'),
]

nelson/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('<slug:slug>/', views.blog_details, name='posts'),
    path('search-blog/', views.SearchBlogView.as_view(), name='searchblog'),
]

nelson/cart/urls.py
from django.urls import path
from .views import AddToCartView, MyCartView, ManageCartView, EmptyCartView

app_name = 'cart'

urlpatterns = [
    path('add-to-cart-<int:product_id>/', AddToCartView.as_view(), name='addtocart'),
    path('', MyCartView.as_view(), name='mycart'),
    path('manage-cart/<int:item_id>/', ManageCartView.as_view(), name='managecart'),
    path('empty-cart/', EmptyCartView.as_view(), name='emptycart')
]

nelson/manager/urls.py
from django.urls import path
from .views import ManagerLoginView, ManagerHomeView, ManagerOrderDetailView, ManagerOrderListView, ManagerOdrerStatusChangeView

app_name = 'manager'

urlpatterns = [
    path('login/', ManagerLoginView.as_view(), name='login'),
    path('home/', ManagerHomeView.as_view(), name='home'),
    path('order/<int:pk>/', ManagerOrderDetailView.as_view(), name='orderdetail'),
    path('all-orders/', ManagerOrderListView.as_view(), name='orderlist'),
    path('order-<int:pk>-change/', ManagerOdrerStatusChangeView.as_view(), name='orderstatuschange')
]

nelson/nelson/urls.py
from django.contrib import admin
from django.urls import path, include
from base.views import AboutView, SearchView, BaseView, FaqView, ContactView
from blog.views import SearchBlogView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', BaseView.as_view()),
    path('home/', BaseView.as_view(), name='home'),
    path('shop/', include('base.urls', namespace='shop')),
    path('about/', AboutView.as_view(), name='about'),
    path('faq/', FaqView.as_view(), name='faq'),
    path('compare/', include('compare.urls', namespace='compare')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('contact/', ContactView.as_view(), name='contact'),
    path('profile/', include('customerprofile.urls', namespace='customerprofile')),
    path('manager/', include('manager.urls', namespace='manager')),
    path('search/', SearchView.as_view(), name='search'),
    path('search-blog/', SearchBlogView.as_view(), name='searchblog')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nelson/blog/models.py
from django.db import models
from django.urls import reverse
import uuid
import os.path


class Blog(models.Model):

    def get_file_name(self, filename: str) -> str:
        ext_file = filename.strip().split('.')[-1]
        new_filename = f'{uuid.uuid4()}.{ext_file}'
        return os.path.join('blog/', new_filename)

    title = models.CharField(max_length=100, db_index=True)
    photo = models.ImageField(upload_to=get_file_name)
    data = models.DateField(auto_now_add=True)
    slug = models.SlugField(max_length=200, db_index=True)
    text = models.TextField(max_length=5000, default='Input text')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        ordering = ('-data', )
        index_together = (('id', 'slug'), )

    def get_absolute_url(self):
        return reverse("blog:posts", args=[self.slug])


class BlogBanner(models.Model):

    def get_file_name(self, filename: str) -> str:
        ext_file = filename.strip().split('.')[-1]
        new_filename = f'{uuid.uuid4()}.{ext_file}'
        return os.path.join('blog_banner/', new_filename)

    title = models.CharField(max_length=20)
    photo = models.ImageField(upload_to=get_file_name)

    def __str__(self):
        return f'{self.title}'

nelson/cart/models.py
from django.db import models
from base.models import Product
from customerprofile.models import Customer


class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Cart: ' + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return 'Cart: ' + str(self.cart.id) + ' CartProduct: ' + str(self.id)

nelson/compare/models.py
from django.db import models

# Create your models here.

nelson/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from base.forms import SubscribeForm
from .models import Blog, BlogBanner
from base.models import BlogDetailBanner
from cart.models import CartProduct, Cart
from django.core.paginator import Paginator
from django.db.models import Q
from django.views.generic import TemplateView


def blog(request):

    if request.method == 'POST':
        subscribe = SubscribeForm(request.POST)
        if subscribe.is_valid():
            subscribe.save()
            return redirect('/')

    blog_banner = BlogBanner.objects.all()
    subscribe = SubscribeForm()
    cart_id = request.session.get('cart_id', None)
    if cart_id:
        cart = Cart.objects.get(id=cart_id)
    else:
        cart = None

    # Set up Pagination
    p = Paginator(Blog.objects.all(), 15)
    page = request.GET.get('page')
    blog_posts = p.get_page(page)
    nums = 'a' * blog_posts.paginator.num_pages

    data = {
        'blog_banner': blog_banner,
        'subscribe_form': subscribe,
        'cart': cart,
        'blog_posts': blog_posts,
        'nums': nums,
    }

    return render(request, 'blog.html', context=data)


def blog_details(request, slug):

    if request.method == 'POST':
        subscribe = SubscribeForm(request.POST)
        if subscribe.is_valid():
            subscribe.save()
            return redirect('/')

    post = get_object_or_404(Blog, slug=slug)
    blog_detail_banner = BlogDetailBanner.objects.all()
    subscribe = SubscribeForm()
    recent_posts = Blog.objects.all()[:4]
    cart_id = request.session.get('cart_id', None)
    if cart_id:
        cart = Cart.objects.get(id=cart_id)
    else:
        cart = None

    data = {
        'post': post,
        'cart': cart,
        'banner': blog_detail_banner,
        'subscribe_form': subscribe,
        'recent_posts': recent_posts,
    }
    return render(request, 'blog-details.html', context=data)


class SearchBlogView(TemplateView):
    template_name = 'search_blog.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        kw = self.request.GET.get('keyword')
        result = Blog.objects.filter(Q(title__icontains=kw) | Q(text__icontains=kw))
        context['result_blog'] = result
        subscribe = SubscribeForm()
        context['subscribe_form'] = subscribe
        cart_id = self.request.session.get('cart_id', None)
        if cart_id:
            cart = Cart.objects.get(id=cart_id)
        else:
            cart = None
        context['cart'] = cart
        return context

    def post(self, request):
        subscribe = SubscribeForm(request.POST)
        if subscribe.is_valid():
            subscribe.save()
            return redirect('/')

nelson/cart/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from base.models import Product, CartBanner
from .models import Cart, CartProduct
from base.forms import SubscribeForm
from django.views.generic import TemplateView, View


class AddToCartView(View):

    success_url = reverse_lazy('shop:shop')

    def get(self, request, **kwargs):

        # get product id from requested url
        product_id = self.kwargs['product_id']

        # get product
        product_obj = Product.objects.get(id=product_id)

        # check if cart exist
        cart_id = self.request.session.get('cart_id', None)
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
            this_product_in_cart = cart_obj.cartproduct_set.filter(product=product_obj)

            # items already exist in cart
            if this_product_in_cart.exists():
                cartproduct = this_product_in_cart.last()
                cartproduct.quantity += 1
                cartproduct.subtotal += product_obj.price
                cartproduct.save()
                cart_obj.total += product_obj.price
                cart_obj.save()

            # new item is added to cart
            else:
                cartproduct = CartProduct.objects.create(
                    cart=cart_obj, product=product_obj, rate=product_obj.price, quantity=1, subtotal=product_obj.price)
                cart_obj.total += product_obj.price
                cart_obj.save()
        else:
            cart_obj = Cart.objects.create(total=0)
            self.request.session['cart_id'] = cart_obj.id
            cartproduct = CartProduct.objects.create(
                cart=cart_obj, product=product_obj, rate=product_obj.price, quantity=1, subtotal=product_obj.price)
            cart_obj.total += product_obj.price
            cart_obj.save()

        return redirect('shop:shop')


class ManageCartView(View):
    def get(self, requset, *args, **kwargs):
        item_id = self.kwargs['item_id']
        action = requset.GET.get('action')
        item_obj = CartProduct.objects.get(id=item_id)
        cart_obj = item_obj.cart

        if action == 'inc':
            item_obj.quantity += 1
            item_obj.subtotal += item_obj.rate
            item_obj.save()
            cart_obj.total += item_obj.rate
            cart_obj.save()
        elif action == 'rmv':
            cart_obj.total -= item_obj.subtotal
            cart_obj.save()
            item_obj.delete()
        elif action == 'dcr':
            item_obj.quantity -= 1
            item_obj.subtotal -= item_obj.rate
            item_obj.save()
            cart_obj.total -= item_obj.rate
            cart_obj.save()
            if item_obj.quantity <= 0:
                item_obj.delete()

        return redirect('cart:mycart')


class MyCartView(TemplateView):
    template_name = 'cart.html'

    def post(self, request):
        subscribe = SubscribeForm(request.POST)
        if subscribe.is_valid():
            subscribe.save()
            return redirect('/')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        subscribe = SubscribeForm()
        context['subscribe_form'] = subscribe
        banner = CartBanner.objects.all()
        context['banner'] = banner
        cart_id = self.request.session.get('cart_id', None)
        if cart_id:
            cart = Cart.objects.get(id=cart_id)
        else:
            cart = None
        context['cart'] = cart

        return context


class EmptyCartView(View):
    def get(self, request, *args, **kwargs):
        cart_id = self.request.session.get('cart_id', None)
        if cart_id:
            cart = Cart.objects.get(id=cart_id)
            cart.cartproduct_set.all().delete()
            cart.total = 0
            cart.save()
        return redirect('cart:mycart')

nelson/compare/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET
from .compare import Compare
from base.models import Product, CompareBanner
from cart.models import CartProduct, Cart
from base.forms import SubscribeForm


@require_GET
def compare_add(request, product_id):
    compare = Compare(request)
    product = get_object_or_404(Product, id=product_id)
    compare.add(product=product)
    return redirect('shop:shop')


def compare_remove(request, product_id):
    compare = Compare(request)
    product = get_object_or_404(Product, id=product_id)
    compare.remove(product)
    return redirect('compare:compare_detail')


def compare_detail(request):

    if request.method == 'POST':
        subscribe = SubscribeForm(request.POST)
        if subscribe.is_valid():
            subscribe.save()
            return redirect('/')

    compare = Compare(request)
    compare_banner = CompareBanner.objects.all()
    subscribe = SubscribeForm()
    cart_id = request.session.get('cart_id', None)
    if cart_id:
        cart = Cart.objects.get(id=cart_id)
    else:
        cart = None

    data = {
        'subscribe_form': subscribe,
        'compare': compare,
        'banner': compare_banner,
        'cart': cart,
    }

    return render(request, 'compare.html', context=data)

nelson/wishlist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET
from .wishlist import Wishlist
from base.models import Product, WishlistBanner
from cart.models import CartProduct, Cart
from base.forms import SubscribeForm


@require_GET
def wishlist_add(request, product_id):
    wishlist = Wishlist(request)
    product = get_object_or_404(Product, id=product_id)
    wishlist.add(product=product)
    return redirect('shop:shop')


def wishlist_remove(request, product_id):
    wishlist = Wishlist(request)
    product = get_object_or_404(Product, id=product_id)
    wishlist.remove(product)
    return redirect('wishlist:wishlist_detail')


def wishlist_detail(request):
    wishlist = Wishlist(request)
    wishlist_banner = WishlistBanner.objects.all()
    subscribe = SubscribeForm()
    cart_id = request.session.get('cart_id', None)
    if cart_id:
        cart = Cart.objects.get(id=cart_id)
    else:
        cart = None

    if request.method == 'POST':
        subscribe = SubscribeForm(request.POST)
        if subscribe.is_valid():
            subscribe.save()
            return redirect('/')

    data = {
        'wishlist': wishlist,
        'cart': cart,
        'banner': wishlist_banner,
        'subscribe_form': subscribe,
    }
    return render(request, 'wishlist.html', context=data)

nelson/templates/manager-order-list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Login Register || nelson</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Place favicon.ico in the root directory -->
    <link href={% static "assets/images/favicon.ico" %} type="img/x-icon" rel="shortcut icon">
    <!-- All css files are included here. -->
    <link rel="stylesheet" href={% static "assets/css/vendor/bootstrap.min.css" %}>
    <link rel="stylesheet" href={% static "assets/css/vendor/iconfont.min.css" %}>
    <link rel="stylesheet" href={% static "assets/css/vendor/helper.css" %}>
    <link rel="stylesheet" href={% static "assets/css/plugins/plugins.css" %}>
    <link rel="stylesheet" href={% static "assets/css/style.css" %}>
    <!-- Modernizr JS -->
    <script src={% static "assets/js/vendor/modernizr-2.8.3.min.js" %}></script>
</head>
<body>
    <!--Header section start-->
    <header class="header header-transparent header-sticky  d-lg-block d-none">
        <div class="header-deafult-area">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-3 col-lg-2 col-md-4 col-12">
                        <!--Logo Area Start-->
                        <div class="logo-area">
                            <a href="{% url 'home' %}"><img src={% static "./assets/images/logo.png" %} alt=""></a>
                        </div>
                        <!--Logo Area End-->
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-4 d-none d-lg-block col-12">
                        <!--Header Menu Area Start-->
                        <div class="header-menu-area text-center">
                            <nav class="main-menu">
                                <ul>
                                    <li><a href="{% url 'manager:home' %}">Головна</a></li>
                                    <li><a href="{% url 'manager:orderlist' %}">Всі замовлення</a></li>
                                    <li><a href="{% url 'home' %}">Перейти на сайт</a></li>
                                </ul>
                            </nav>
                        </div>
                        <!--Header Menu Area End-->
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!--Header section end-->

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>Всі замовлення</h3>
                <table class="table">
                    <thead>
                    <tr>
                        <th>№</th>
                        <th>ID</th>
                        <th>Клієнт</th>
                        <th>Дата замовлення</th>
                        <th>Вартість</th>
                        <th>Статус</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for order in allorders %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td><a href="{% url 'manager:orderdetail' order.id %}">#ID_{{ order.id }}</a></td>
                            <td>{{ order.first_name }} {{ order.last_name }}</td>
                            <td>{{ order.timestamp }}</td>
                            <td>{{ order.total }} грн</td>
                            <td>{{ order.status }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!--Footer section start-->
    <footer class="footer-section section bg-gray">

        <!--Footer bottom start-->
        <div class="footer-bottom section">
            <div class="container">
                <div class="row no-gutters">
                    <div class="col-12 ft-border pt-25 pb-25">
                        <div class="row justify-content-between align-items-center">
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="copyright text-left">
                                    <p>Copyright &copy;2019 <a href="{% url 'home' %}">nelson</a>. All rights reserved.</p>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="payment-getway text-lg-right text-center">
                                    <img src={% static "./assets/images/payment.png" %} alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--Footer bottom end-->

    </footer>
    <!--Footer section end-->

    <!-- Placed js at the end of the document so the pages load faster -->

    <!-- All jquery file included here -->
    <script src={% static "assets/js/vendor/jquery-1.12.4.min.js" %}></script>
    <script src="https://maps.google.com/maps/api/js?sensor=false&libraries=geometry&v=3.22&key=AIzaSyDAq7MrCR1A2qIShmjbtLHSKjcEIEBEEwM"></script>
    <script src={% static "assets/js/vendor/popper.min.js" %}></script>
    <script src={% static "assets/js/vendor/bootstrap.min.js" %}></script>
    <script src={% static "assets/js/plugins/plugins.js" %}></script>
    <script src={% static "assets/js/main.js" %}></script>
</body>
</html>